spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create
  data:
    rest:
      base-path: /api
